services:
  - type: web
    name: music-copyright-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn MusicCopyrightDetectorSystem.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: MusicCopyrightDetectorSystem.settings
      - key: PYTHON_VERSION
        value: 3.12.6
