# Generated by Django 5.0.14 on 2025-06-20 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_report_copyrightid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFingerprint',
            fields=[
                ('FingerprintID', models.AutoField(primary_key=True, serialize=False)),
                ('Hash', models.CharField(max_length=255)),
                ('Offset', models.IntegerField()),
                ('MusicFileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector.musicfile')),
            ],
            options={
                'indexes': [models.Index(fields=['Hash'], name='detector_au_Hash_371bf6_idx')],
            },
        ),
    ]
