# Generated by Django 5.0.14 on 2025-06-20 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_audiofingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofingerprint',
            name='CopyrightedMusicID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detector.copyrightedmusic'),
        ),
        migrations.AlterField(
            model_name='audiofingerprint',
            name='MusicFileID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detector.musicfile'),
        ),
    ]
