# Generated by Django 5.0.14 on 2025-06-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_audiofingerprint_copyrightedmusicid_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='audiofingerprint',
            index=models.Index(fields=['Hash', 'MusicFileID'], name='detector_au_Hash_a66f4e_idx'),
        ),
    ]
