# Generated by Django 5.0.14 on 2025-06-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_audiofingerprint_detector_au_hash_a66f4e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='MatchedOffset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='audiofingerprint',
            index=models.Index(fields=['Hash', 'CopyrightedMusicID'], name='detector_au_Hash_296fe3_idx'),
        ),
    ]
