# Generated by Django 5.0.14 on 2025-07-04 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_analysis_matchedoffset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notification_pref', models.CharField(choices=[('all', 'All Notifications'), ('important', 'Only Important'), ('none', 'None')], default='all', max_length=20)),
                ('theme', models.CharField(choices=[('system', 'System Theme'), ('light', 'Light Theme'), ('dark', 'Dark Theme')], default='system', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserSettings',
            },
        ),
    ]
